using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace VocabGrid.Migrations
{
    /// <inheritdoc />
    public partial class AddConceptModel : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_UserWordProgresses_UserID_WordID",
                table: "UserWordProgresses");

            migrationBuilder.AlterColumn<int>(
                name: "WordID",
                table: "UserWordProgresses",
                type: "int",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int");

            migrationBuilder.AddColumn<int>(
                name: "ConceptId",
                table: "UserWordProgresses",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "LanguageCode",
                table: "UserWordProgresses",
                type: "nvarchar(450)",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "Concepts",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Key = table.Column<string>(type: "nvarchar(60)", maxLength: 60, nullable: false),
                    CategoryId = table.Column<int>(type: "int", nullable: true),
                    Level = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    OrderIndex = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Concepts", x => x.Id);
                    table.CheckConstraint("CK_Concept_KeyNotBlank", "LEN(LTRIM(RTRIM([Key]))) > 0");
                    table.CheckConstraint("CK_Concept_Level", "[Level] IN ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')");
                    table.CheckConstraint("CK_Concept_OrderIndex", "[OrderIndex] >= 0");
                    table.ForeignKey(
                        name: "FK_Concepts_Categories_CategoryId",
                        column: x => x.CategoryId,
                        principalTable: "Categories",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.SetNull);
                });

            migrationBuilder.CreateTable(
                name: "ConceptTranslations",
                columns: table => new
                {
                    ConceptId = table.Column<int>(type: "int", nullable: false),
                    LanguageCode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    Term = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    ExampleSentence = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    AudioUrl = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ConceptTranslations", x => new { x.ConceptId, x.LanguageCode });
                    table.CheckConstraint("CK_ConceptTranslation_TermNotBlank", "LEN(LTRIM(RTRIM([Term]))) > 0");
                    table.ForeignKey(
                        name: "FK_ConceptTranslations_Concepts_ConceptId",
                        column: x => x.ConceptId,
                        principalTable: "Concepts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_ConceptTranslations_Languages_LanguageCode",
                        column: x => x.LanguageCode,
                        principalTable: "Languages",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.InsertData(
                table: "Concepts",
                columns: new[] { "Id", "CategoryId", "Key", "Level", "OrderIndex" },
                values: new object[,]
                {
                    { 1, 12, "greetings_hello", "A1", 1 },
                    { 2, 12, "greetings_good_morning", "A1", 2 },
                    { 3, 12, "greetings_good_evening", "A1", 3 },
                    { 4, 12, "greetings_good_night", "A1", 4 },
                    { 5, 12, "greetings_goodbye", "A1", 5 },
                    { 6, 12, "greetings_thank_you", "A1", 6 },
                    { 7, 12, "greetings_please", "A1", 7 },
                    { 8, 12, "greetings_sorry", "A1", 8 },
                    { 9, 12, "greetings_excuse_me", "A1", 9 },
                    { 10, 12, "greetings_yes", "A1", 10 },
                    { 11, 12, "greetings_no", "A1", 11 },
                    { 12, 12, "greetings_welcome", "A1", 12 },
                    { 13, 1, "food_basics_water", "A1", 13 },
                    { 14, 1, "food_basics_bread", "A1", 14 },
                    { 15, 1, "food_basics_milk", "A1", 15 },
                    { 16, 1, "food_basics_tea", "A1", 16 },
                    { 17, 1, "food_basics_coffee", "A1", 17 },
                    { 18, 1, "food_basics_apple", "A1", 18 },
                    { 19, 1, "food_basics_cheese", "A1", 19 },
                    { 20, 1, "food_basics_egg", "A1", 20 },
                    { 21, 1, "food_basics_rice", "A1", 21 },
                    { 22, 1, "food_basics_meat", "A1", 22 },
                    { 23, 1, "food_basics_salt", "A1", 23 },
                    { 24, 1, "food_basics_sugar", "A1", 24 },
                    { 25, 5, "numbers_one", "A1", 25 },
                    { 26, 5, "numbers_two", "A1", 26 },
                    { 27, 5, "numbers_three", "A1", 27 },
                    { 28, 5, "numbers_four", "A1", 28 },
                    { 29, 5, "numbers_five", "A1", 29 },
                    { 30, 5, "numbers_six", "A1", 30 },
                    { 31, 5, "numbers_seven", "A1", 31 },
                    { 32, 5, "numbers_eight", "A1", 32 },
                    { 33, 5, "numbers_nine", "A1", 33 },
                    { 34, 5, "numbers_ten", "A1", 34 },
                    { 35, 5, "numbers_hundred", "A1", 35 },
                    { 36, 5, "numbers_thousand", "A1", 36 },
                    { 37, 5, "time_and_days_today", "A1", 37 },
                    { 38, 5, "time_and_days_tomorrow", "A1", 38 },
                    { 39, 5, "time_and_days_yesterday", "A1", 39 },
                    { 40, 5, "time_and_days_monday", "A1", 40 },
                    { 41, 5, "time_and_days_tuesday", "A1", 41 },
                    { 42, 5, "time_and_days_wednesday", "A1", 42 },
                    { 43, 5, "time_and_days_thursday", "A1", 43 },
                    { 44, 5, "time_and_days_friday", "A1", 44 },
                    { 45, 5, "time_and_days_saturday", "A1", 45 },
                    { 46, 5, "time_and_days_sunday", "A1", 46 },
                    { 47, 5, "time_and_days_week", "A1", 47 },
                    { 48, 5, "time_and_days_month", "A1", 48 },
                    { 49, 12, "family_mother", "A1", 49 },
                    { 50, 12, "family_father", "A1", 50 },
                    { 51, 12, "family_sister", "A1", 51 },
                    { 52, 12, "family_brother", "A1", 52 },
                    { 53, 12, "family_daughter", "A1", 53 },
                    { 54, 12, "family_son", "A1", 54 },
                    { 55, 12, "family_grandmother", "A1", 55 },
                    { 56, 12, "family_grandfather", "A1", 56 },
                    { 57, 12, "family_spouse", "A1", 57 },
                    { 58, 12, "family_child", "A1", 58 },
                    { 59, 12, "family_friend", "A1", 59 },
                    { 60, 12, "family_family", "A1", 60 },
                    { 61, 5, "colours_red", "A1", 61 },
                    { 62, 5, "colours_blue", "A1", 62 },
                    { 63, 5, "colours_green", "A1", 63 },
                    { 64, 5, "colours_yellow", "A1", 64 },
                    { 65, 5, "colours_black", "A1", 65 },
                    { 66, 5, "colours_white", "A1", 66 },
                    { 67, 5, "colours_orange", "A1", 67 },
                    { 68, 5, "colours_purple", "A1", 68 },
                    { 69, 5, "colours_brown", "A1", 69 },
                    { 70, 5, "colours_grey", "A1", 70 },
                    { 71, 2, "travel_and_directions_airport", "A2", 71 },
                    { 72, 2, "travel_and_directions_station", "A2", 72 },
                    { 73, 2, "travel_and_directions_ticket", "A2", 73 },
                    { 74, 2, "travel_and_directions_hotel", "A2", 74 },
                    { 75, 2, "travel_and_directions_left", "A2", 75 },
                    { 76, 2, "travel_and_directions_right", "A2", 76 },
                    { 77, 2, "travel_and_directions_straight", "A2", 77 },
                    { 78, 2, "travel_and_directions_map", "A2", 78 },
                    { 79, 2, "travel_and_directions_luggage", "A2", 79 },
                    { 80, 2, "travel_and_directions_passport", "A2", 80 },
                    { 81, 2, "travel_and_directions_road", "A2", 81 },
                    { 82, 2, "travel_and_directions_bridge", "A2", 82 },
                    { 83, 3, "work_and_school_work", "A2", 83 },
                    { 84, 3, "work_and_school_office", "A2", 84 },
                    { 85, 3, "work_and_school_meeting", "A2", 85 },
                    { 86, 5, "work_and_school_teacher", "A2", 86 },
                    { 87, 5, "work_and_school_student", "A2", 87 },
                    { 88, 5, "work_and_school_school", "A2", 88 },
                    { 89, 5, "work_and_school_book", "A2", 89 },
                    { 90, 5, "work_and_school_pen", "A2", 90 },
                    { 91, 5, "work_and_school_question", "A2", 91 },
                    { 92, 5, "work_and_school_answer", "A2", 92 },
                    { 93, 5, "work_and_school_exam", "A2", 93 },
                    { 94, 5, "work_and_school_homework", "A2", 94 },
                    { 95, 10, "body_and_health_head", "A2", 95 },
                    { 96, 10, "body_and_health_hand", "A2", 96 },
                    { 97, 10, "body_and_health_eye", "A2", 97 },
                    { 98, 10, "body_and_health_ear", "A2", 98 },
                    { 99, 10, "body_and_health_heart", "A2", 99 },
                    { 100, 10, "body_and_health_doctor", "A2", 100 },
                    { 101, 10, "body_and_health_hospital", "A2", 101 },
                    { 102, 10, "body_and_health_medicine", "A2", 102 },
                    { 103, 10, "body_and_health_pain", "A2", 103 },
                    { 104, 10, "body_and_health_fever", "A2", 104 },
                    { 105, 10, "body_and_health_foot", "A2", 105 },
                    { 106, 10, "body_and_health_tooth", "A2", 106 },
                    { 107, 12, "home_and_daily_life_house", "A2", 107 },
                    { 108, 12, "home_and_daily_life_door", "A2", 108 },
                    { 109, 12, "home_and_daily_life_window", "A2", 109 },
                    { 110, 12, "home_and_daily_life_kitchen", "A2", 110 },
                    { 111, 12, "home_and_daily_life_table", "A2", 111 },
                    { 112, 12, "home_and_daily_life_chair", "A2", 112 },
                    { 113, 12, "home_and_daily_life_bed", "A2", 113 },
                    { 114, 12, "home_and_daily_life_key", "A2", 114 },
                    { 115, 12, "home_and_daily_life_room", "A2", 115 },
                    { 116, 12, "home_and_daily_life_garden", "A2", 116 },
                    { 117, 12, "home_and_daily_life_car", "A2", 117 },
                    { 118, 12, "home_and_daily_life_money", "A2", 118 },
                    { 119, 13, "weather_rain", "B1", 119 },
                    { 120, 13, "weather_snow", "B1", 120 },
                    { 121, 13, "weather_sun", "B1", 121 },
                    { 122, 13, "weather_cloud", "B1", 122 },
                    { 123, 13, "weather_wind", "B1", 123 },
                    { 124, 13, "weather_storm", "B1", 124 },
                    { 125, 13, "weather_fog", "B1", 125 },
                    { 126, 13, "weather_temperature", "B1", 126 },
                    { 127, 13, "weather_umbrella", "B1", 127 },
                    { 128, 13, "weather_season", "B1", 128 },
                    { 129, 13, "weather_warm", "B1", 129 },
                    { 130, 13, "weather_freezing", "B1", 130 },
                    { 131, 12, "feelings_happy", "B1", 131 },
                    { 132, 12, "feelings_sad", "B1", 132 },
                    { 133, 12, "feelings_angry", "B1", 133 },
                    { 134, 12, "feelings_tired", "B1", 134 },
                    { 135, 12, "feelings_afraid", "B1", 135 },
                    { 136, 12, "feelings_surprised", "B1", 136 },
                    { 137, 12, "feelings_excited", "B1", 137 },
                    { 138, 12, "feelings_bored", "B1", 138 },
                    { 139, 12, "feelings_proud", "B1", 139 },
                    { 140, 12, "feelings_calm", "B1", 140 },
                    { 141, 12, "feelings_worried", "B1", 141 },
                    { 142, 12, "feelings_lonely", "B1", 142 },
                    { 143, 11, "shopping_price", "B1", 143 },
                    { 144, 11, "shopping_discount", "B1", 144 },
                    { 145, 11, "shopping_receipt", "B1", 145 },
                    { 146, 11, "shopping_cash", "B1", 146 },
                    { 147, 11, "shopping_size", "B1", 147 },
                    { 148, 11, "shopping_shop", "B1", 148 },
                    { 149, 11, "shopping_customer", "B1", 149 },
                    { 150, 11, "shopping_expensive", "B1", 150 },
                    { 151, 11, "shopping_cheap", "B1", 151 },
                    { 152, 11, "shopping_refund", "B1", 152 },
                    { 153, 11, "shopping_queue", "B1", 153 },
                    { 154, 11, "shopping_delivery", "B1", 154 },
                    { 155, 4, "technology_computer", "B1", 155 },
                    { 156, 4, "technology_screen", "B1", 156 },
                    { 157, 4, "technology_keyboard", "B1", 157 },
                    { 158, 4, "technology_password", "B1", 158 },
                    { 159, 4, "technology_file", "B1", 159 },
                    { 160, 4, "technology_message", "B1", 160 },
                    { 161, 4, "technology_battery", "B1", 161 },
                    { 162, 4, "technology_software", "B1", 162 },
                    { 163, 4, "technology_network", "B1", 163 },
                    { 164, 4, "technology_download", "B1", 164 },
                    { 165, 4, "technology_update", "B1", 165 },
                    { 166, 4, "technology_device", "B1", 166 },
                    { 167, 13, "nature_tree", "B1", 167 },
                    { 168, 13, "nature_flower", "B1", 168 },
                    { 169, 13, "nature_river", "B1", 169 },
                    { 170, 13, "nature_mountain", "B1", 170 },
                    { 171, 13, "nature_sea", "B1", 171 },
                    { 172, 13, "nature_forest", "B1", 172 },
                    { 173, 13, "nature_sky", "B1", 173 },
                    { 174, 13, "nature_stone", "B1", 174 },
                    { 175, 13, "nature_lake", "B1", 175 },
                    { 176, 13, "nature_island", "B1", 176 },
                    { 177, 13, "nature_beach", "B1", 177 },
                    { 178, 13, "nature_valley", "B1", 178 },
                    { 179, 9, "sports_team", "B2", 179 },
                    { 180, 9, "sports_player", "B2", 180 },
                    { 181, 9, "sports_match", "B2", 181 },
                    { 182, 9, "sports_goal", "B2", 182 },
                    { 183, 9, "sports_coach", "B2", 183 },
                    { 184, 9, "sports_training", "B2", 184 },
                    { 185, 9, "sports_score", "B2", 185 },
                    { 186, 9, "sports_stadium", "B2", 186 },
                    { 187, 9, "sports_referee", "B2", 187 },
                    { 188, 9, "sports_victory", "B2", 188 },
                    { 189, 9, "sports_defeat", "B2", 189 },
                    { 190, 9, "sports_injury", "B2", 190 },
                    { 191, 7, "music_and_art_song", "B2", 191 },
                    { 192, 7, "music_and_art_singer", "B2", 192 },
                    { 193, 7, "music_and_art_guitar", "B2", 193 },
                    { 194, 7, "music_and_art_concert", "B2", 194 },
                    { 195, 7, "music_and_art_painting", "B2", 195 },
                    { 196, 7, "music_and_art_artist", "B2", 196 },
                    { 197, 7, "music_and_art_museum", "B2", 197 },
                    { 198, 7, "music_and_art_stage", "B2", 198 },
                    { 199, 7, "music_and_art_rhythm", "B2", 199 },
                    { 200, 7, "music_and_art_audience", "B2", 200 },
                    { 201, 7, "music_and_art_exhibition", "B2", 201 },
                    { 202, 7, "music_and_art_sculpture", "B2", 202 },
                    { 203, 1, "cooking_recipe", "B2", 203 },
                    { 204, 1, "cooking_knife", "B2", 204 },
                    { 205, 1, "cooking_plate", "B2", 205 },
                    { 206, 1, "cooking_spoon", "B2", 206 },
                    { 207, 1, "cooking_fork", "B2", 207 },
                    { 208, 1, "cooking_oven", "B2", 208 },
                    { 209, 1, "cooking_boil", "B2", 209 },
                    { 210, 1, "cooking_fry", "B2", 210 },
                    { 211, 1, "cooking_taste", "B2", 211 },
                    { 212, 1, "cooking_fresh", "B2", 212 },
                    { 213, 1, "cooking_delicious", "B2", 213 },
                    { 214, 1, "cooking_ingredient", "B2", 214 },
                    { 215, 3, "money_and_banking_bank", "B2", 215 },
                    { 216, 3, "money_and_banking_account", "B2", 216 },
                    { 217, 3, "money_and_banking_salary", "B2", 217 },
                    { 218, 3, "money_and_banking_loan", "B2", 218 },
                    { 219, 3, "money_and_banking_invoice", "B2", 219 },
                    { 220, 3, "money_and_banking_payment", "B2", 220 },
                    { 221, 3, "money_and_banking_savings", "B2", 221 },
                    { 222, 3, "money_and_banking_debt", "B2", 222 },
                    { 223, 3, "money_and_banking_budget", "B2", 223 },
                    { 224, 3, "money_and_banking_currency", "B2", 224 },
                    { 225, 3, "money_and_banking_tax", "B2", 225 },
                    { 226, 3, "money_and_banking_transfer", "B2", 226 },
                    { 227, 5, "communication_letter", "B2", 227 },
                    { 228, 5, "communication_conversation", "B2", 228 },
                    { 229, 5, "communication_advice", "B2", 229 },
                    { 230, 5, "communication_news", "B2", 230 },
                    { 231, 5, "communication_story", "B2", 231 },
                    { 232, 5, "communication_opinion", "B2", 232 },
                    { 233, 5, "communication_translation", "B2", 233 },
                    { 234, 5, "communication_speech", "B2", 234 },
                    { 235, 5, "communication_explain", "B2", 235 },
                    { 236, 5, "communication_repeat", "B2", 236 },
                    { 237, 5, "communication_agree", "B2", 237 },
                    { 238, 5, "communication_disagree", "B2", 238 },
                    { 239, 15, "animals_dog", "A2", 239 },
                    { 240, 15, "animals_cat", "A2", 240 },
                    { 241, 15, "animals_bird", "A2", 241 },
                    { 242, 15, "animals_fish", "A2", 242 },
                    { 243, 15, "animals_horse", "A2", 243 },
                    { 244, 15, "animals_sheep", "A2", 244 },
                    { 245, 15, "animals_cow", "A2", 245 },
                    { 246, 15, "animals_chicken", "A2", 246 },
                    { 247, 15, "animals_rabbit", "A2", 247 },
                    { 248, 15, "animals_bear", "A2", 248 },
                    { 249, 15, "animals_wolf", "A2", 249 },
                    { 250, 15, "animals_lion", "A2", 250 },
                    { 251, 14, "science_science", "B1", 251 },
                    { 252, 14, "science_research", "B1", 252 },
                    { 253, 14, "science_experiment", "B1", 253 },
                    { 254, 14, "science_theory", "B1", 254 },
                    { 255, 14, "science_energy", "B1", 255 },
                    { 256, 14, "science_gravity", "B1", 256 },
                    { 257, 14, "science_cell", "B1", 257 },
                    { 258, 14, "science_atom", "B1", 258 },
                    { 259, 14, "science_planet", "B1", 259 },
                    { 260, 14, "science_chemistry", "B1", 260 },
                    { 261, 14, "science_biology", "B1", 261 },
                    { 262, 14, "science_evidence", "B1", 262 },
                    { 263, 6, "film_and_cinema_film", "B1", 263 },
                    { 264, 6, "film_and_cinema_cinema", "B1", 264 },
                    { 265, 6, "film_and_cinema_actor", "B1", 265 },
                    { 266, 6, "film_and_cinema_director", "B1", 266 },
                    { 267, 6, "film_and_cinema_scene", "B1", 267 },
                    { 268, 6, "film_and_cinema_subtitle", "B1", 268 },
                    { 269, 6, "film_and_cinema_comedy", "B1", 269 },
                    { 270, 6, "film_and_cinema_drama", "B1", 270 },
                    { 271, 6, "film_and_cinema_series", "B1", 271 },
                    { 272, 6, "film_and_cinema_episode", "B1", 272 },
                    { 273, 6, "film_and_cinema_ending", "B1", 273 },
                    { 274, 6, "film_and_cinema_character", "B1", 274 },
                    { 275, 8, "gaming_game", "B1", 275 },
                    { 276, 8, "gaming_level", "B1", 276 },
                    { 277, 8, "gaming_console", "B1", 277 },
                    { 278, 8, "gaming_controller", "B1", 278 },
                    { 279, 8, "gaming_mission", "B1", 279 },
                    { 280, 8, "gaming_reward", "B1", 280 },
                    { 281, 8, "gaming_tournament", "B1", 281 },
                    { 282, 8, "gaming_achievement", "B1", 282 },
                    { 283, 8, "gaming_puzzle", "B1", 283 },
                    { 284, 8, "gaming_strategy", "B1", 284 },
                    { 285, 8, "gaming_opponent", "B1", 285 },
                    { 286, 8, "gaming_challenge", "B1", 286 }
                });

            migrationBuilder.InsertData(
                table: "ConceptTranslations",
                columns: new[] { "ConceptId", "LanguageCode", "AudioUrl", "ExampleSentence", "Term" },
                values: new object[,]
                {
                    { 1, "de", null, "Hallo, schön dich kennenzulernen.", "Hallo" },
                    { 1, "en", null, "Hello, nice to meet you.", "Hello" },
                    { 1, "es", null, "Hola, encantado de conocerte.", "Hola" },
                    { 1, "fr", null, "Bonjour, enchanté de vous rencontrer.", "Bonjour" },
                    { 1, "tr", null, null, "Merhaba" },
                    { 2, "de", null, "Guten Morgen, hast du gut geschlafen?", "Guten Morgen" },
                    { 2, "en", null, "Good morning, did you sleep well?", "Good morning" },
                    { 2, "es", null, "Buenos días, ¿has dormido bien?", "Buenos días" },
                    { 2, "fr", null, "Bonjour, avez-vous bien dormi ?", "Bonjour" },
                    { 2, "tr", null, null, "Günaydın" },
                    { 3, "de", null, "Guten Abend, kommen Sie bitte herein.", "Guten Abend" },
                    { 3, "en", null, "Good evening, please come in.", "Good evening" },
                    { 3, "es", null, "Buenas tardes, pase usted.", "Buenas tardes" },
                    { 3, "fr", null, "Bonsoir, entrez je vous prie.", "Bonsoir" },
                    { 3, "tr", null, null, "İyi akşamlar" },
                    { 4, "de", null, "Gute Nacht, bis morgen.", "Gute Nacht" },
                    { 4, "en", null, "Good night, see you tomorrow.", "Good night" },
                    { 4, "es", null, "Buenas noches, hasta mañana.", "Buenas noches" },
                    { 4, "fr", null, "Bonne nuit, à demain.", "Bonne nuit" },
                    { 4, "tr", null, null, "İyi geceler" },
                    { 5, "de", null, "Auf Wiedersehen, pass auf dich auf.", "Auf Wiedersehen" },
                    { 5, "en", null, "Goodbye, take care of yourself.", "Goodbye" },
                    { 5, "es", null, "Adiós, cuídate mucho.", "Adiós" },
                    { 5, "fr", null, "Au revoir, prenez soin de vous.", "Au revoir" },
                    { 5, "tr", null, null, "Hoşça kal" },
                    { 6, "de", null, "Danke für deine ganze Hilfe.", "Danke" },
                    { 6, "en", null, "Thank you for all your help.", "Thank you" },
                    { 6, "es", null, "Gracias por toda tu ayuda.", "Gracias" },
                    { 6, "fr", null, "Merci pour toute votre aide.", "Merci" },
                    { 6, "tr", null, null, "Teşekkürler" },
                    { 7, "de", null, "Bitte warten Sie hier einen Moment.", "Bitte" },
                    { 7, "en", null, "Please wait here for a moment.", "Please" },
                    { 7, "es", null, "Por favor, espere aquí un momento.", "Por favor" },
                    { 7, "fr", null, "S'il vous plaît, attendez ici un instant.", "S'il vous plaît" },
                    { 7, "tr", null, null, "Lütfen" },
                    { 8, "de", null, "Entschuldigung, ich komme zu spät.", "Entschuldigung" },
                    { 8, "en", null, "Sorry, I am running late.", "Sorry" },
                    { 8, "es", null, "Lo siento, voy con retraso.", "Lo siento" },
                    { 8, "fr", null, "Désolé, je suis en retard.", "Désolé" },
                    { 8, "tr", null, null, "Özür dilerim" },
                    { 9, "de", null, "Entschuldigen Sie, wo ist der Bahnhof?", "Entschuldigen Sie" },
                    { 9, "en", null, "Excuse me, where is the station?", "Excuse me" },
                    { 9, "es", null, "Perdone, ¿dónde está la estación?", "Perdone" },
                    { 9, "fr", null, "Excusez-moi, où est la gare ?", "Excusez-moi" },
                    { 9, "tr", null, null, "Affedersiniz" },
                    { 10, "de", null, "Ja, das klingt gut für mich.", "Ja" },
                    { 10, "en", null, "Yes, that sounds good to me.", "Yes" },
                    { 10, "es", null, "Sí, me parece bien.", "Sí" },
                    { 10, "fr", null, "Oui, cela me convient.", "Oui" },
                    { 10, "tr", null, null, "Evet" },
                    { 11, "de", null, "Nein, vielen Dank.", "Nein" },
                    { 11, "en", null, "No, thank you very much.", "No" },
                    { 11, "es", null, "No, muchas gracias.", "No" },
                    { 11, "fr", null, "Non, merci beaucoup.", "Non" },
                    { 11, "tr", null, null, "Hayır" },
                    { 12, "de", null, "Willkommen in unserem Haus.", "Willkommen" },
                    { 12, "en", null, "Welcome to our home.", "Welcome" },
                    { 12, "es", null, "Bienvenido a nuestra casa.", "Bienvenido" },
                    { 12, "fr", null, "Bienvenue chez nous.", "Bienvenue" },
                    { 12, "tr", null, null, "Hoş geldiniz" },
                    { 13, "en", null, "Could I have a glass of water?", "Water" },
                    { 13, "tr", null, null, "Su" },
                    { 14, "en", null, "The bread is still warm.", "Bread" },
                    { 14, "tr", null, null, "Ekmek" },
                    { 15, "en", null, "She drinks milk every morning.", "Milk" },
                    { 15, "tr", null, null, "Süt" },
                    { 16, "en", null, "Would you like a cup of tea?", "Tea" },
                    { 16, "tr", null, null, "Çay" },
                    { 17, "en", null, "I drink coffee after lunch.", "Coffee" },
                    { 17, "tr", null, null, "Kahve" },
                    { 18, "en", null, "This apple is very sweet.", "Apple" },
                    { 18, "tr", null, null, "Elma" },
                    { 19, "en", null, "We bought cheese and olives.", "Cheese" },
                    { 19, "tr", null, null, "Peynir" },
                    { 20, "en", null, "He ate one egg for breakfast.", "Egg" },
                    { 20, "tr", null, null, "Yumurta" },
                    { 21, "en", null, "The rice is cooked with butter.", "Rice" },
                    { 21, "tr", null, null, "Pirinç" },
                    { 22, "en", null, "The meat is on the grill.", "Meat" },
                    { 22, "tr", null, null, "Et" },
                    { 23, "en", null, "Please pass me the salt.", "Salt" },
                    { 23, "tr", null, null, "Tuz" },
                    { 24, "en", null, "No sugar in my coffee, thanks.", "Sugar" },
                    { 24, "tr", null, null, "Şeker" },
                    { 25, "en", null, "I only need one ticket.", "One" },
                    { 25, "tr", null, null, "Bir" },
                    { 26, "en", null, "We waited two hours.", "Two" },
                    { 26, "tr", null, null, "İki" },
                    { 27, "en", null, "There are three rooms upstairs.", "Three" },
                    { 27, "tr", null, null, "Üç" },
                    { 28, "en", null, "The table seats four people.", "Four" },
                    { 28, "tr", null, null, "Dört" },
                    { 29, "en", null, "The shop opens at five.", "Five" },
                    { 29, "tr", null, null, "Beş" },
                    { 30, "en", null, "She has six brothers and sisters.", "Six" },
                    { 30, "tr", null, null, "Altı" },
                    { 31, "en", null, "The week has seven days.", "Seven" },
                    { 31, "tr", null, null, "Yedi" },
                    { 32, "en", null, "He works eight hours a day.", "Eight" },
                    { 32, "tr", null, null, "Sekiz" },
                    { 33, "en", null, "The train leaves at nine.", "Nine" },
                    { 33, "tr", null, null, "Dokuz" },
                    { 34, "en", null, "Give me ten minutes.", "Ten" },
                    { 34, "tr", null, null, "On" },
                    { 35, "en", null, "The book has a hundred pages.", "Hundred" },
                    { 35, "tr", null, null, "Yüz" },
                    { 36, "en", null, "A thousand people came.", "Thousand" },
                    { 36, "tr", null, null, "Bin" },
                    { 37, "en", null, "Today is a busy day.", "Today" },
                    { 37, "tr", null, null, "Bugün" },
                    { 38, "en", null, "We will finish it tomorrow.", "Tomorrow" },
                    { 38, "tr", null, null, "Yarın" },
                    { 39, "en", null, "Yesterday it rained all day.", "Yesterday" },
                    { 39, "tr", null, null, "Dün" },
                    { 40, "en", null, "The course starts on Monday.", "Monday" },
                    { 40, "tr", null, null, "Pazartesi" },
                    { 41, "en", null, "I have a meeting on Tuesday.", "Tuesday" },
                    { 41, "tr", null, null, "Salı" },
                    { 42, "en", null, "Wednesday is my day off.", "Wednesday" },
                    { 42, "tr", null, null, "Çarşamba" },
                    { 43, "en", null, "We travel on Thursday.", "Thursday" },
                    { 43, "tr", null, null, "Perşembe" },
                    { 44, "en", null, "The office closes early on Friday.", "Friday" },
                    { 44, "tr", null, null, "Cuma" },
                    { 45, "en", null, "On Saturday we visit my parents.", "Saturday" },
                    { 45, "tr", null, null, "Cumartesi" },
                    { 46, "en", null, "Sunday is for resting.", "Sunday" },
                    { 46, "tr", null, null, "Pazar" },
                    { 47, "en", null, "I will be away for a week.", "Week" },
                    { 47, "tr", null, null, "Hafta" },
                    { 48, "en", null, "The rent is due every month.", "Month" },
                    { 48, "tr", null, null, "Ay" },
                    { 49, "en", null, "My mother is a teacher.", "Mother" },
                    { 49, "tr", null, null, "Anne" },
                    { 50, "en", null, "His father works at the hospital.", "Father" },
                    { 50, "tr", null, null, "Baba" },
                    { 51, "en", null, "My sister lives abroad.", "Sister" },
                    { 51, "tr", null, null, "Kız kardeş" },
                    { 52, "en", null, "Her brother plays football.", "Brother" },
                    { 52, "tr", null, null, "Erkek kardeş" },
                    { 53, "en", null, "Their daughter starts school today.", "Daughter" },
                    { 53, "tr", null, null, "Kız evlat" },
                    { 54, "en", null, "Our son is learning to drive.", "Son" },
                    { 54, "tr", null, null, "Oğul" },
                    { 55, "en", null, "My grandmother makes wonderful soup.", "Grandmother" },
                    { 55, "tr", null, null, "Büyükanne" },
                    { 56, "en", null, "Grandfather tells the best stories.", "Grandfather" },
                    { 56, "tr", null, null, "Büyükbaba" },
                    { 57, "en", null, "My spouse is waiting outside.", "Spouse" },
                    { 57, "tr", null, null, "Eş" },
                    { 58, "en", null, "The child is asleep.", "Child" },
                    { 58, "tr", null, null, "Çocuk" },
                    { 59, "en", null, "A friend is coming for dinner.", "Friend" },
                    { 59, "tr", null, null, "Arkadaş" },
                    { 60, "en", null, "The whole family came together.", "Family" },
                    { 60, "tr", null, null, "Aile" },
                    { 61, "en", null, "She wore a red coat.", "Red" },
                    { 61, "tr", null, null, "Kırmızı" },
                    { 62, "en", null, "The sky is clear and blue.", "Blue" },
                    { 62, "tr", null, null, "Mavi" },
                    { 63, "en", null, "The garden is very green.", "Green" },
                    { 63, "tr", null, null, "Yeşil" },
                    { 64, "en", null, "He painted the door yellow.", "Yellow" },
                    { 64, "tr", null, null, "Sarı" },
                    { 65, "en", null, "I bought black shoes.", "Black" },
                    { 65, "tr", null, null, "Siyah" },
                    { 66, "en", null, "The walls are white.", "White" },
                    { 66, "tr", null, null, "Beyaz" },
                    { 67, "en", null, "The sunset turned orange.", "Orange" },
                    { 67, "tr", null, null, "Turuncu" },
                    { 68, "en", null, "These flowers are purple.", "Purple" },
                    { 68, "tr", null, null, "Mor" },
                    { 69, "en", null, "He has brown eyes.", "Brown" },
                    { 69, "tr", null, null, "Kahverengi" },
                    { 70, "en", null, "The sky looks grey today.", "Grey" },
                    { 70, "tr", null, null, "Gri" },
                    { 71, "en", null, "The airport is far from the centre.", "Airport" },
                    { 71, "tr", null, null, "Havalimanı" },
                    { 72, "en", null, "We met at the station.", "Station" },
                    { 72, "tr", null, null, "İstasyon" },
                    { 73, "en", null, "I bought a return ticket.", "Ticket" },
                    { 73, "tr", null, null, "Bilet" },
                    { 74, "en", null, "The hotel is next to the museum.", "Hotel" },
                    { 74, "tr", null, null, "Otel" },
                    { 75, "en", null, "Turn left at the corner.", "Left" },
                    { 75, "tr", null, null, "Sol" },
                    { 76, "en", null, "The bank is on your right.", "Right" },
                    { 76, "tr", null, null, "Sağ" },
                    { 77, "en", null, "Go straight for two streets.", "Straight" },
                    { 77, "tr", null, null, "Düz" },
                    { 78, "en", null, "Let me look at the map.", "Map" },
                    { 78, "tr", null, null, "Harita" },
                    { 79, "en", null, "My luggage is still in the car.", "Luggage" },
                    { 79, "tr", null, null, "Bavul" },
                    { 80, "en", null, "Please show me your passport.", "Passport" },
                    { 80, "tr", null, null, "Pasaport" },
                    { 81, "en", null, "This road leads to the sea.", "Road" },
                    { 81, "tr", null, null, "Yol" },
                    { 82, "en", null, "We crossed the old bridge.", "Bridge" },
                    { 82, "tr", null, null, "Köprü" },
                    { 83, "en", null, "I start work at nine.", "Work" },
                    { 83, "tr", null, null, "İş" },
                    { 84, "en", null, "Her office is on the third floor.", "Office" },
                    { 84, "tr", null, null, "Ofis" },
                    { 85, "en", null, "The meeting lasted an hour.", "Meeting" },
                    { 85, "tr", null, null, "Toplantı" },
                    { 86, "en", null, "Our teacher explained it twice.", "Teacher" },
                    { 86, "tr", null, null, "Öğretmen" },
                    { 87, "en", null, "Every student needs a notebook.", "Student" },
                    { 87, "tr", null, null, "Öğrenci" },
                    { 88, "en", null, "The school is closed today.", "School" },
                    { 88, "tr", null, null, "Okul" },
                    { 89, "en", null, "This book is easy to read.", "Book" },
                    { 89, "tr", null, null, "Kitap" },
                    { 90, "en", null, "Can I borrow your pen?", "Pen" },
                    { 90, "tr", null, null, "Kalem" },
                    { 91, "en", null, "That is a good question.", "Question" },
                    { 91, "tr", null, null, "Soru" },
                    { 92, "en", null, "I do not know the answer.", "Answer" },
                    { 92, "tr", null, null, "Cevap" },
                    { 93, "en", null, "The exam starts at ten.", "Exam" },
                    { 93, "tr", null, null, "Sınav" },
                    { 94, "en", null, "He finished his homework early.", "Homework" },
                    { 94, "tr", null, null, "Ödev" },
                    { 95, "en", null, "My head hurts a little.", "Head" },
                    { 95, "tr", null, null, "Baş" },
                    { 96, "en", null, "Wash your hands before dinner.", "Hand" },
                    { 96, "tr", null, null, "El" },
                    { 97, "en", null, "Something is in my eye.", "Eye" },
                    { 97, "tr", null, null, "Göz" },
                    { 98, "en", null, "He whispered in my ear.", "Ear" },
                    { 98, "tr", null, null, "Kulak" },
                    { 99, "en", null, "The doctor listened to my heart.", "Heart" },
                    { 99, "tr", null, null, "Kalp" },
                    { 100, "en", null, "You should see a doctor.", "Doctor" },
                    { 100, "tr", null, null, "Doktor" },
                    { 101, "en", null, "The hospital is open all night.", "Hospital" },
                    { 101, "tr", null, null, "Hastane" },
                    { 102, "en", null, "Take this medicine after meals.", "Medicine" },
                    { 102, "tr", null, null, "İlaç" },
                    { 103, "en", null, "The pain is much better now.", "Pain" },
                    { 103, "tr", null, null, "Ağrı" },
                    { 104, "en", null, "The child has a fever.", "Fever" },
                    { 104, "tr", null, null, "Ateş" },
                    { 105, "en", null, "My left foot is swollen.", "Foot" },
                    { 105, "tr", null, null, "Ayak" },
                    { 106, "en", null, "This tooth has been hurting.", "Tooth" },
                    { 106, "tr", null, null, "Diş" },
                    { 107, "en", null, "Their house has a red roof.", "House" },
                    { 107, "tr", null, null, "Ev" },
                    { 108, "en", null, "Please close the door.", "Door" },
                    { 108, "tr", null, null, "Kapı" },
                    { 109, "en", null, "Open the window for some air.", "Window" },
                    { 109, "tr", null, null, "Pencere" },
                    { 110, "en", null, "She is cooking in the kitchen.", "Kitchen" },
                    { 110, "tr", null, null, "Mutfak" },
                    { 111, "en", null, "Put the plates on the table.", "Table" },
                    { 111, "tr", null, null, "Masa" },
                    { 112, "en", null, "This chair is broken.", "Chair" },
                    { 112, "tr", null, null, "Sandalye" },
                    { 113, "en", null, "The bed is by the window.", "Bed" },
                    { 113, "tr", null, null, "Yatak" },
                    { 114, "en", null, "I cannot find my key.", "Key" },
                    { 114, "tr", null, null, "Anahtar" },
                    { 115, "en", null, "The room is very quiet.", "Room" },
                    { 115, "tr", null, null, "Oda" },
                    { 116, "en", null, "We had tea in the garden.", "Garden" },
                    { 116, "tr", null, null, "Bahçe" },
                    { 117, "en", null, "The car will not start.", "Car" },
                    { 117, "tr", null, null, "Araba" },
                    { 118, "en", null, "I forgot my money at home.", "Money" },
                    { 118, "tr", null, null, "Para" },
                    { 119, "en", null, "The rain started just after lunch.", "Rain" },
                    { 119, "tr", null, null, "Yağmur" },
                    { 120, "en", null, "The snow covered the whole garden.", "Snow" },
                    { 120, "tr", null, null, "Kar" },
                    { 121, "en", null, "The sun came out in the afternoon.", "Sun" },
                    { 121, "tr", null, null, "Güneş" },
                    { 122, "en", null, "A dark cloud is coming from the west.", "Cloud" },
                    { 122, "tr", null, null, "Bulut" },
                    { 123, "en", null, "The wind is strong near the coast.", "Wind" },
                    { 123, "tr", null, null, "Rüzgâr" },
                    { 124, "en", null, "The storm lasted all night.", "Storm" },
                    { 124, "tr", null, null, "Fırtına" },
                    { 125, "en", null, "Thick fog closed the airport.", "Fog" },
                    { 125, "tr", null, null, "Sis" },
                    { 126, "en", null, "The temperature drops quickly at night.", "Temperature" },
                    { 126, "tr", null, null, "Sıcaklık" },
                    { 127, "en", null, "Take an umbrella, it might rain.", "Umbrella" },
                    { 127, "tr", null, null, "Şemsiye" },
                    { 128, "en", null, "Spring is my favourite season.", "Season" },
                    { 128, "tr", null, null, "Mevsim" },
                    { 129, "en", null, "The water is warm enough to swim.", "Warm" },
                    { 129, "tr", null, null, "Ilık" },
                    { 130, "en", null, "It was freezing on the mountain.", "Freezing" },
                    { 130, "tr", null, null, "Dondurucu" },
                    { 131, "en", null, "She looked happy with the result.", "Happy" },
                    { 131, "tr", null, null, "Mutlu" },
                    { 132, "en", null, "He felt sad after the news.", "Sad" },
                    { 132, "tr", null, null, "Üzgün" },
                    { 133, "en", null, "Do not answer while you are angry.", "Angry" },
                    { 133, "tr", null, null, "Kızgın" },
                    { 134, "en", null, "I am too tired to study tonight.", "Tired" },
                    { 134, "tr", null, null, "Yorgun" },
                    { 135, "en", null, "The child was afraid of the dark.", "Afraid" },
                    { 135, "tr", null, null, "Korkmuş" },
                    { 136, "en", null, "We were surprised by the question.", "Surprised" },
                    { 136, "tr", null, null, "Şaşkın" },
                    { 137, "en", null, "They are excited about the trip.", "Excited" },
                    { 137, "tr", null, null, "Heyecanlı" },
                    { 138, "en", null, "He got bored during the lecture.", "Bored" },
                    { 138, "tr", null, null, "Sıkılmış" },
                    { 139, "en", null, "Her parents are proud of her.", "Proud" },
                    { 139, "tr", null, null, "Gururlu" },
                    { 140, "en", null, "Try to stay calm and breathe.", "Calm" },
                    { 140, "tr", null, null, "Sakin" },
                    { 141, "en", null, "I am worried about the exam.", "Worried" },
                    { 141, "tr", null, null, "Endişeli" },
                    { 142, "en", null, "He felt lonely in the new city.", "Lonely" },
                    { 142, "tr", null, null, "Yalnız" },
                    { 143, "en", null, "The price includes delivery.", "Price" },
                    { 143, "tr", null, null, "Fiyat" },
                    { 144, "en", null, "Students get a small discount.", "Discount" },
                    { 144, "tr", null, null, "İndirim" },
                    { 145, "en", null, "Keep the receipt for the return.", "Receipt" },
                    { 145, "tr", null, null, "Fiş" },
                    { 146, "en", null, "I would rather pay in cash.", "Cash" },
                    { 146, "tr", null, null, "Nakit" },
                    { 147, "en", null, "Do you have this in a larger size?", "Size" },
                    { 147, "tr", null, null, "Beden" },
                    { 148, "en", null, "The shop closes at seven.", "Shop" },
                    { 148, "tr", null, null, "Dükkân" },
                    { 149, "en", null, "The customer asked for a refund.", "Customer" },
                    { 149, "tr", null, null, "Müşteri" },
                    { 150, "en", null, "That jacket is too expensive.", "Expensive" },
                    { 150, "tr", null, null, "Pahalı" },
                    { 151, "en", null, "The market is cheaper than the mall.", "Cheap" },
                    { 151, "tr", null, null, "Ucuz" },
                    { 152, "en", null, "They agreed to a full refund.", "Refund" },
                    { 152, "tr", null, null, "İade" },
                    { 153, "en", null, "There was a long queue at the till.", "Queue" },
                    { 153, "tr", null, null, "Kuyruk" },
                    { 154, "en", null, "Delivery takes three working days.", "Delivery" },
                    { 154, "tr", null, null, "Teslimat" },
                    { 155, "en", null, "My computer restarted by itself.", "Computer" },
                    { 155, "tr", null, null, "Bilgisayar" },
                    { 156, "en", null, "The screen is too bright at night.", "Screen" },
                    { 156, "tr", null, null, "Ekran" },
                    { 157, "en", null, "This keyboard is very quiet.", "Keyboard" },
                    { 157, "tr", null, null, "Klavye" },
                    { 158, "en", null, "Never share your password.", "Password" },
                    { 158, "tr", null, null, "Parola" },
                    { 159, "en", null, "Save the file before you close it.", "File" },
                    { 159, "tr", null, null, "Dosya" },
                    { 160, "en", null, "I sent you a message this morning.", "Message" },
                    { 160, "tr", null, null, "Mesaj" },
                    { 161, "en", null, "The battery lasts about a day.", "Battery" },
                    { 161, "tr", null, null, "Pil" },
                    { 162, "en", null, "The software needs an update.", "Software" },
                    { 162, "tr", null, null, "Yazılım" },
                    { 163, "en", null, "The network is down again.", "Network" },
                    { 163, "tr", null, null, "Ağ" },
                    { 164, "en", null, "Download the file and open it.", "Download" },
                    { 164, "tr", null, null, "İndirmek" },
                    { 165, "en", null, "The update fixed the problem.", "Update" },
                    { 165, "tr", null, null, "Güncelleme" },
                    { 166, "en", null, "You can use two devices at once.", "Device" },
                    { 166, "tr", null, null, "Cihaz" },
                    { 167, "en", null, "An old tree stands by the gate.", "Tree" },
                    { 167, "tr", null, null, "Ağaç" },
                    { 168, "en", null, "She picked a flower for her mother.", "Flower" },
                    { 168, "tr", null, null, "Çiçek" },
                    { 169, "en", null, "The river runs through the town.", "River" },
                    { 169, "tr", null, null, "Nehir" },
                    { 170, "en", null, "We climbed the mountain in summer.", "Mountain" },
                    { 170, "tr", null, null, "Dağ" },
                    { 171, "en", null, "The sea was calm that morning.", "Sea" },
                    { 171, "tr", null, null, "Deniz" },
                    { 172, "en", null, "The forest is quiet after the rain.", "Forest" },
                    { 172, "tr", null, null, "Orman" },
                    { 173, "en", null, "The sky turned orange at sunset.", "Sky" },
                    { 173, "tr", null, null, "Gökyüzü" },
                    { 174, "en", null, "He threw a stone into the water.", "Stone" },
                    { 174, "tr", null, null, "Taş" },
                    { 175, "en", null, "We swam in the lake all afternoon.", "Lake" },
                    { 175, "tr", null, null, "Göl" },
                    { 176, "en", null, "The island is an hour away by boat.", "Island" },
                    { 176, "tr", null, null, "Ada" },
                    { 177, "en", null, "The beach was empty in October.", "Beach" },
                    { 177, "tr", null, null, "Plaj" },
                    { 178, "en", null, "A narrow road crosses the valley.", "Valley" },
                    { 178, "tr", null, null, "Vadi" },
                    { 179, "en", null, "Our team plays on Saturday.", "Team" },
                    { 179, "tr", null, null, "Takım" },
                    { 180, "en", null, "That player scored twice.", "Player" },
                    { 180, "tr", null, null, "Oyuncu" },
                    { 181, "en", null, "The match ended in a draw.", "Match" },
                    { 181, "tr", null, null, "Maç" },
                    { 182, "en", null, "He scored a goal in the last minute.", "Goal" },
                    { 182, "tr", null, null, "Gol" },
                    { 183, "en", null, "The coach changed the whole plan.", "Coach" },
                    { 183, "tr", null, null, "Antrenör" },
                    { 184, "en", null, "Training starts at six in the morning.", "Training" },
                    { 184, "tr", null, null, "Antrenman" },
                    { 185, "en", null, "What was the final score?", "Score" },
                    { 185, "tr", null, null, "Skor" },
                    { 186, "en", null, "The stadium was completely full.", "Stadium" },
                    { 186, "tr", null, null, "Stadyum" },
                    { 187, "en", null, "The referee stopped the game.", "Referee" },
                    { 187, "tr", null, null, "Hakem" },
                    { 188, "en", null, "It was an easy victory.", "Victory" },
                    { 188, "tr", null, null, "Zafer" },
                    { 189, "en", null, "The defeat surprised everyone.", "Defeat" },
                    { 189, "tr", null, null, "Yenilgi" },
                    { 190, "en", null, "An injury kept him out for a month.", "Injury" },
                    { 190, "tr", null, null, "Sakatlık" },
                    { 191, "en", null, "That song was written in the sixties.", "Song" },
                    { 191, "tr", null, null, "Şarkı" },
                    { 192, "en", null, "The singer forgot the second verse.", "Singer" },
                    { 192, "tr", null, null, "Şarkıcı" },
                    { 193, "en", null, "He plays the guitar every evening.", "Guitar" },
                    { 193, "tr", null, null, "Gitar" },
                    { 194, "en", null, "The concert sold out in an hour.", "Concert" },
                    { 194, "tr", null, null, "Konser" },
                    { 195, "en", null, "The painting hangs in the hall.", "Painting" },
                    { 195, "tr", null, null, "Tablo" },
                    { 196, "en", null, "The artist works with old photographs.", "Artist" },
                    { 196, "tr", null, null, "Sanatçı" },
                    { 197, "en", null, "The museum is free on Mondays.", "Museum" },
                    { 197, "tr", null, null, "Müze" },
                    { 198, "en", null, "She walked onto the stage slowly.", "Stage" },
                    { 198, "tr", null, null, "Sahne" },
                    { 199, "en", null, "The rhythm changes in the chorus.", "Rhythm" },
                    { 199, "tr", null, null, "Ritim" },
                    { 200, "en", null, "The audience stood up and clapped.", "Audience" },
                    { 200, "tr", null, null, "Seyirci" },
                    { 201, "en", null, "The exhibition closes next week.", "Exhibition" },
                    { 201, "tr", null, null, "Sergi" },
                    { 202, "en", null, "A stone sculpture stands in the square.", "Sculpture" },
                    { 202, "tr", null, null, "Heykel" },
                    { 203, "en", null, "This recipe takes twenty minutes.", "Recipe" },
                    { 203, "tr", null, null, "Tarif" },
                    { 204, "en", null, "Use a sharp knife for the onions.", "Knife" },
                    { 204, "tr", null, null, "Bıçak" },
                    { 205, "en", null, "Put the bread on a clean plate.", "Plate" },
                    { 205, "tr", null, null, "Tabak" },
                    { 206, "en", null, "Add two spoons of sugar.", "Spoon" },
                    { 206, "tr", null, null, "Kaşık" },
                    { 207, "en", null, "The fork fell under the table.", "Fork" },
                    { 207, "tr", null, null, "Çatal" },
                    { 208, "en", null, "Heat the oven before you start.", "Oven" },
                    { 208, "tr", null, null, "Fırın" },
                    { 209, "en", null, "Boil the water for five minutes.", "Boil" },
                    { 209, "tr", null, null, "Kaynatmak" },
                    { 210, "en", null, "Fry the eggs in a little oil.", "Fry" },
                    { 210, "tr", null, null, "Kızartmak" },
                    { 211, "en", null, "The soup has a strong taste.", "Taste" },
                    { 211, "tr", null, null, "Tat" },
                    { 212, "en", null, "The bread is fresh from this morning.", "Fresh" },
                    { 212, "tr", null, null, "Taze" },
                    { 213, "en", null, "Everything on the table was delicious.", "Delicious" },
                    { 213, "tr", null, null, "Lezzetli" },
                    { 214, "en", null, "One ingredient is missing.", "Ingredient" },
                    { 214, "tr", null, null, "Malzeme" },
                    { 215, "en", null, "The bank opens at nine.", "Bank" },
                    { 215, "tr", null, null, "Banka" },
                    { 216, "en", null, "I opened a second account.", "Account" },
                    { 216, "tr", null, null, "Hesap" },
                    { 217, "en", null, "The salary arrives on the first.", "Salary" },
                    { 217, "tr", null, null, "Maaş" },
                    { 218, "en", null, "They took a loan for the house.", "Loan" },
                    { 218, "tr", null, null, "Kredi" },
                    { 219, "en", null, "Send the invoice by email.", "Invoice" },
                    { 219, "tr", null, null, "Fatura" },
                    { 220, "en", null, "The payment did not go through.", "Payment" },
                    { 220, "tr", null, null, "Ödeme" },
                    { 221, "en", null, "She keeps her savings in the bank.", "Savings" },
                    { 221, "tr", null, null, "Birikim" },
                    { 222, "en", null, "He paid off the last of his debt.", "Debt" },
                    { 222, "tr", null, null, "Borç" },
                    { 223, "en", null, "The trip is outside our budget.", "Budget" },
                    { 223, "tr", null, null, "Bütçe" },
                    { 224, "en", null, "Which currency do they use there?", "Currency" },
                    { 224, "tr", null, null, "Para birimi" },
                    { 225, "en", null, "The tax is included in the price.", "Tax" },
                    { 225, "tr", null, null, "Vergi" },
                    { 226, "en", null, "The transfer takes one working day.", "Transfer" },
                    { 226, "tr", null, null, "Havale" },
                    { 227, "en", null, "A letter arrived from the school.", "Letter" },
                    { 227, "tr", null, null, "Mektup" },
                    { 228, "en", null, "We had a long conversation.", "Conversation" },
                    { 228, "tr", null, null, "Sohbet" },
                    { 229, "en", null, "Her advice saved me a lot of time.", "Advice" },
                    { 229, "tr", null, null, "Tavsiye" },
                    { 230, "en", null, "The news spread very quickly.", "News" },
                    { 230, "tr", null, null, "Haber" },
                    { 231, "en", null, "He told the same story twice.", "Story" },
                    { 231, "tr", null, null, "Hikâye" },
                    { 232, "en", null, "Everyone gave a different opinion.", "Opinion" },
                    { 232, "tr", null, null, "Görüş" },
                    { 233, "en", null, "The translation is not quite right.", "Translation" },
                    { 233, "tr", null, null, "Çeviri" },
                    { 234, "en", null, "His speech lasted ten minutes.", "Speech" },
                    { 234, "tr", null, null, "Konuşma" },
                    { 235, "en", null, "Can you explain that again?", "Explain" },
                    { 235, "tr", null, null, "Açıklamak" },
                    { 236, "en", null, "Please repeat the last sentence.", "Repeat" },
                    { 236, "tr", null, null, "Tekrarlamak" },
                    { 237, "en", null, "I agree with most of your points.", "Agree" },
                    { 237, "tr", null, null, "Katılmak" },
                    { 238, "en", null, "It is fine to disagree politely.", "Disagree" },
                    { 238, "tr", null, null, "Karşı çıkmak" },
                    { 239, "en", null, "The dog waited by the door.", "Dog" },
                    { 239, "tr", null, null, "Köpek" },
                    { 240, "en", null, "Their cat sleeps all afternoon.", "Cat" },
                    { 240, "tr", null, null, "Kedi" },
                    { 241, "en", null, "A bird built its nest in the tree.", "Bird" },
                    { 241, "tr", null, null, "Kuş" },
                    { 242, "en", null, "We caught three fish in the lake.", "Fish" },
                    { 242, "tr", null, null, "Balık" },
                    { 243, "en", null, "The horse ran across the field.", "Horse" },
                    { 243, "tr", null, null, "At" },
                    { 244, "en", null, "The sheep stayed close together.", "Sheep" },
                    { 244, "tr", null, null, "Koyun" },
                    { 245, "en", null, "The cow is grazing near the fence.", "Cow" },
                    { 245, "tr", null, null, "İnek" },
                    { 246, "en", null, "The chicken laid an egg this morning.", "Chicken" },
                    { 246, "tr", null, null, "Tavuk" },
                    { 247, "en", null, "A rabbit disappeared into the bushes.", "Rabbit" },
                    { 247, "tr", null, null, "Tavşan" },
                    { 248, "en", null, "The bear searched for food by the river.", "Bear" },
                    { 248, "tr", null, null, "Ayı" },
                    { 249, "en", null, "A wolf howled somewhere in the forest.", "Wolf" },
                    { 249, "tr", null, null, "Kurt" },
                    { 250, "en", null, "The lion rested under a tree.", "Lion" },
                    { 250, "tr", null, null, "Aslan" },
                    { 251, "en", null, "Science explains how the world works.", "Science" },
                    { 251, "tr", null, null, "Bilim" },
                    { 252, "en", null, "Her research took almost three years.", "Research" },
                    { 252, "tr", null, null, "Araştırma" },
                    { 253, "en", null, "The experiment gave a surprising result.", "Experiment" },
                    { 253, "tr", null, null, "Deney" },
                    { 254, "en", null, "This theory is still being tested.", "Theory" },
                    { 254, "tr", null, null, "Kuram" },
                    { 255, "en", null, "The sun gives us energy every day.", "Energy" },
                    { 255, "tr", null, null, "Enerji" },
                    { 256, "en", null, "Gravity pulls everything towards the ground.", "Gravity" },
                    { 256, "tr", null, null, "Yerçekimi" },
                    { 257, "en", null, "Every living thing is made of cells.", "Cell" },
                    { 257, "tr", null, null, "Hücre" },
                    { 258, "en", null, "An atom is far too small to see.", "Atom" },
                    { 258, "tr", null, null, "Atom" },
                    { 259, "en", null, "Our planet is mostly covered by water.", "Planet" },
                    { 259, "tr", null, null, "Gezegen" },
                    { 260, "en", null, "She teaches chemistry at the university.", "Chemistry" },
                    { 260, "tr", null, null, "Kimya" },
                    { 261, "en", null, "Biology is the study of living things.", "Biology" },
                    { 261, "tr", null, null, "Biyoloji" },
                    { 262, "en", null, "There is strong evidence for this idea.", "Evidence" },
                    { 262, "tr", null, null, "Kanıt" },
                    { 263, "en", null, "The film lasted almost three hours.", "Film" },
                    { 263, "tr", null, null, "Film" },
                    { 264, "en", null, "There is a new cinema near the park.", "Cinema" },
                    { 264, "tr", null, null, "Sinema" },
                    { 265, "en", null, "The actor learned the whole script.", "Actor" },
                    { 265, "tr", null, null, "Oyuncu" },
                    { 266, "en", null, "The director shot the scene twice.", "Director" },
                    { 266, "tr", null, null, "Yönetmen" },
                    { 267, "en", null, "That scene was filmed in one take.", "Scene" },
                    { 267, "tr", null, null, "Sahne" },
                    { 268, "en", null, "I watch films with subtitles.", "Subtitle" },
                    { 268, "tr", null, null, "Altyazı" },
                    { 269, "en", null, "We chose a comedy for the evening.", "Comedy" },
                    { 269, "tr", null, null, "Komedi" },
                    { 270, "en", null, "The drama moved everyone in the room.", "Drama" },
                    { 270, "tr", null, null, "Dram" },
                    { 271, "en", null, "The series has four seasons.", "Series" },
                    { 271, "tr", null, null, "Dizi" },
                    { 272, "en", null, "The last episode airs on Sunday.", "Episode" },
                    { 272, "tr", null, null, "Bölüm" },
                    { 273, "en", null, "Nobody expected that ending.", "Ending" },
                    { 273, "tr", null, null, "Son" },
                    { 274, "en", null, "My favourite character appears late.", "Character" },
                    { 274, "tr", null, null, "Karakter" },
                    { 275, "en", null, "The game takes about ten hours.", "Game" },
                    { 275, "tr", null, null, "Oyun" },
                    { 276, "en", null, "He finished the last level yesterday.", "Level" },
                    { 276, "tr", null, null, "Seviye" },
                    { 277, "en", null, "The console is connected to the television.", "Console" },
                    { 277, "tr", null, null, "Konsol" },
                    { 278, "en", null, "My controller needs new batteries.", "Controller" },
                    { 278, "tr", null, null, "Kumanda" },
                    { 279, "en", null, "This mission is harder than the others.", "Mission" },
                    { 279, "tr", null, null, "Görev" },
                    { 280, "en", null, "You get a reward for finishing early.", "Reward" },
                    { 280, "tr", null, null, "Ödül" },
                    { 281, "en", null, "The tournament starts next weekend.", "Tournament" },
                    { 281, "tr", null, null, "Turnuva" },
                    { 282, "en", null, "She unlocked every achievement.", "Achievement" },
                    { 282, "tr", null, null, "Başarım" },
                    { 283, "en", null, "The puzzle took me an hour to solve.", "Puzzle" },
                    { 283, "tr", null, null, "Bulmaca" },
                    { 284, "en", null, "A better strategy would save time.", "Strategy" },
                    { 284, "tr", null, null, "Strateji" },
                    { 285, "en", null, "My opponent played very carefully.", "Opponent" },
                    { 285, "tr", null, null, "Rakip" },
                    { 286, "en", null, "The final challenge is optional.", "Challenge" },
                    { 286, "tr", null, null, "Meydan okuma" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_UserWordProgresses_ConceptId",
                table: "UserWordProgresses",
                column: "ConceptId");

            migrationBuilder.CreateIndex(
                name: "IX_UserWordProgresses_UserID_ConceptId_LanguageCode",
                table: "UserWordProgresses",
                columns: new[] { "UserID", "ConceptId", "LanguageCode" },
                unique: true,
                filter: "[ConceptId] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_UserWordProgresses_UserID_WordID",
                table: "UserWordProgresses",
                columns: new[] { "UserID", "WordID" },
                unique: true,
                filter: "[WordID] IS NOT NULL");

            migrationBuilder.AddCheckConstraint(
                name: "CK_UserWordProgress_CardOrConcept",
                table: "UserWordProgresses",
                sql: "([WordID] IS NOT NULL AND [ConceptId] IS NULL AND [LanguageCode] IS NULL) OR ([WordID] IS NULL AND [ConceptId] IS NOT NULL AND [LanguageCode] IS NOT NULL)");

            migrationBuilder.CreateIndex(
                name: "IX_Concepts_CategoryId_OrderIndex",
                table: "Concepts",
                columns: new[] { "CategoryId", "OrderIndex" });

            migrationBuilder.CreateIndex(
                name: "IX_Concepts_Key",
                table: "Concepts",
                column: "Key",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_ConceptTranslations_LanguageCode",
                table: "ConceptTranslations",
                column: "LanguageCode");

            migrationBuilder.AddForeignKey(
                name: "FK_UserWordProgresses_Concepts_ConceptId",
                table: "UserWordProgresses",
                column: "ConceptId",
                principalTable: "Concepts",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_UserWordProgresses_Concepts_ConceptId",
                table: "UserWordProgresses");

            migrationBuilder.DropTable(
                name: "ConceptTranslations");

            migrationBuilder.DropTable(
                name: "Concepts");

            migrationBuilder.DropIndex(
                name: "IX_UserWordProgresses_ConceptId",
                table: "UserWordProgresses");

            migrationBuilder.DropIndex(
                name: "IX_UserWordProgresses_UserID_ConceptId_LanguageCode",
                table: "UserWordProgresses");

            migrationBuilder.DropIndex(
                name: "IX_UserWordProgresses_UserID_WordID",
                table: "UserWordProgresses");

            migrationBuilder.DropCheckConstraint(
                name: "CK_UserWordProgress_CardOrConcept",
                table: "UserWordProgresses");

            migrationBuilder.DropColumn(
                name: "ConceptId",
                table: "UserWordProgresses");

            migrationBuilder.DropColumn(
                name: "LanguageCode",
                table: "UserWordProgresses");

            migrationBuilder.AlterColumn<int>(
                name: "WordID",
                table: "UserWordProgresses",
                type: "int",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_UserWordProgresses_UserID_WordID",
                table: "UserWordProgresses",
                columns: new[] { "UserID", "WordID" },
                unique: true);
        }
    }
}
