// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using LanGigaCards.Api.Data;

#nullable disable

namespace LanGigaCards.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260808183423_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LanGigaCards.Api.Entities.Lesson", b =>
                {
                    b.Property<int>("LessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonID");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.LessonVocabulary", b =>
                {
                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<int>("WordID")
                        .HasColumnType("int");

                    b.Property<int>("VocabularyWordID")
                        .HasColumnType("int");

                    b.HasKey("LessonID", "WordID");

                    b.HasIndex("VocabularyWordID");

                    b.ToTable("LessonVocabularies");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Quiz", b =>
                {
                    b.Property<int>("QuizID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizID"));

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuizID");

                    b.HasIndex("LessonID");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.QuizOption", b =>
                {
                    b.Property<int>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionID"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.HasKey("OptionID");

                    b.HasIndex("QuizID");

                    b.ToTable("QuizOption");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserProgress", b =>
                {
                    b.Property<int>("ProgressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressID"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastAccess")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ProgressID");

                    b.HasIndex("LessonID");

                    b.HasIndex("UserID");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserWordProgress", b =>
                {
                    b.Property<long>("UserWordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserWordID"));

                    b.Property<DateTime>("LastReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MasteryLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("VocabularyWordID")
                        .HasColumnType("int");

                    b.Property<int>("WordID")
                        .HasColumnType("int");

                    b.HasKey("UserWordID");

                    b.HasIndex("UserID");

                    b.HasIndex("VocabularyWordID");

                    b.ToTable("UserWordProgresses");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Vocabulary", b =>
                {
                    b.Property<int>("WordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordID"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExampleSentence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WordID");

                    b.ToTable("Vocabularies");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEarned")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Study 7 days in a row",
                            Icon = "flame_icon",
                            IsEarned = true,
                            Name = "7-Day Streak"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Get 100% on a quiz",
                            Icon = "star_icon",
                            IsEarned = true,
                            Name = "Perfect Score"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Learn 100 words",
                            Icon = "book_icon",
                            IsEarned = true,
                            Name = "Word Collector"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Finish 20 cards in 5 min",
                            Icon = "zap_icon",
                            IsEarned = false,
                            Name = "Speed Learner"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Start a 2nd language",
                            Icon = "globe_icon",
                            IsEarned = false,
                            Name = "Polyglot"
                        });
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Food & Dining Vocabulary",
                            IsSelected = true,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Travel & Tourism Vocabulary",
                            IsSelected = true,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Professional & Work Vocabulary",
                            IsSelected = true,
                            Name = "Business"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tech & IT Vocabulary",
                            IsSelected = false,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Academic & School Vocabulary",
                            IsSelected = false,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Cinema & Entertainment",
                            IsSelected = false,
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Music & Songs",
                            IsSelected = false,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Video Games & Gaming Culture",
                            IsSelected = false,
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Sports & Fitness",
                            IsSelected = false,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Health & Medicine",
                            IsSelected = false,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Shopping & Fashion",
                            IsSelected = false,
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Family & Relationships",
                            IsSelected = false,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Nature & Environment",
                            IsSelected = false,
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Science & Research",
                            IsSelected = false,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Animals & Wildlife",
                            IsSelected = false,
                            Name = "Animals"
                        });
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<int>("DailyGoalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("NativeLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserCategory", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("UserCategories");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.LessonVocabulary", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.Lesson", "Lesson")
                        .WithMany("LessonVocabularies")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanGigaCards.Api.Entities.Vocabulary", "Vocabulary")
                        .WithMany("LessonVocabularies")
                        .HasForeignKey("VocabularyWordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Quiz", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.Lesson", "Lesson")
                        .WithMany("Quizzes")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.QuizOption", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.Quiz", "Quiz")
                        .WithMany("Options")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserProgress", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.Lesson", "Lesson")
                        .WithMany("UserProgresses")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanGigaCards.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserWordProgress", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LanGigaCards.Api.Entities.Vocabulary", "Vocabulary")
                        .WithMany("UserWordProgresses")
                        .HasForeignKey("VocabularyWordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserCategory", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.Category", "Category")
                        .WithMany("UserCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanGigaCards.Api.Entities.User", "User")
                        .WithMany("UserCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Lesson", b =>
                {
                    b.Navigation("LessonVocabularies");

                    b.Navigation("Quizzes");

                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Quiz", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Vocabulary", b =>
                {
                    b.Navigation("LessonVocabularies");

                    b.Navigation("UserWordProgresses");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Category", b =>
                {
                    b.Navigation("UserCategories");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.User", b =>
                {
                    b.Navigation("UserCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
