// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using LanGigaCards.Api.Data;

#nullable disable

namespace LanGigaCards.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812211916_SeedLessonsAndQuizzes")]
    partial class SeedLessonsAndQuizzes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LanGigaCards.Api.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.Property<string>("UnlockCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Study 7 days in a row",
                            Icon = "flame_icon",
                            Name = "7-Day Streak",
                            Threshold = 7,
                            UnlockCondition = "StreakDays"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Get 100% on a quiz",
                            Icon = "star_icon",
                            Name = "Perfect Score",
                            Threshold = 100,
                            UnlockCondition = "PerfectQuiz"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Learn 100 words",
                            Icon = "book_icon",
                            Name = "Word Collector",
                            Threshold = 100,
                            UnlockCondition = "WordsLearned"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Finish 20 cards in 5 min",
                            Icon = "zap_icon",
                            Name = "Speed Learner",
                            Threshold = 20,
                            UnlockCondition = "CardsInMinutes"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Start a 2nd language",
                            Icon = "globe_icon",
                            Name = "Polyglot",
                            Threshold = 2,
                            UnlockCondition = "LanguagesStarted"
                        });
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Food & Dining Vocabulary",
                            Name = "Food"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Travel & Tourism Vocabulary",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Professional & Work Vocabulary",
                            Name = "Business"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tech & IT Vocabulary",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Academic & School Vocabulary",
                            Name = "Education"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Cinema & Entertainment",
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Music & Songs",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Video Games & Gaming Culture",
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Sports & Fitness",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Health & Medicine",
                            Name = "Health"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Shopping & Fashion",
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Family & Relationships",
                            Name = "Family"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Nature & Environment",
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Science & Research",
                            Name = "Science"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Animals & Wildlife",
                            Name = "Animals"
                        });
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.LearningPurpose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LearningPurposes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Travel and tourism",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Work and professional use",
                            Name = "Business"
                        },
                        new
                        {
                            Id = 3,
                            Description = "School and exams",
                            Name = "Academic"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Everyday speaking",
                            Name = "Daily Conversation"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Media, culture and hobbies",
                            Name = "Culture"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Living abroad",
                            Name = "Relocation"
                        });
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Lesson", b =>
                {
                    b.Property<int>("LessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonID");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            LessonID = 1,
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Basic hello and introductions",
                            Level = "A1",
                            OrderIndex = 1,
                            Title = "Greetings"
                        },
                        new
                        {
                            LessonID = 2,
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Common food and drink words",
                            Level = "A1",
                            OrderIndex = 2,
                            Title = "Food Basics"
                        });
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.LessonVocabulary", b =>
                {
                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<int>("WordID")
                        .HasColumnType("int");

                    b.HasKey("LessonID", "WordID");

                    b.HasIndex("WordID");

                    b.ToTable("LessonVocabularies");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Quiz", b =>
                {
                    b.Property<int>("QuizID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizID"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeLimitSeconds")
                        .HasColumnType("int");

                    b.HasKey("QuizID");

                    b.HasIndex("LessonID");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            QuizID = 1,
                            LessonID = 1,
                            Points = 1,
                            QuestionText = "What does 'Merhaba' mean?",
                            QuestionType = "MultipleChoice",
                            TimeLimitSeconds = 20
                        },
                        new
                        {
                            QuizID = 2,
                            LessonID = 1,
                            Points = 1,
                            QuestionText = "How do you say 'Good morning' in Turkish?",
                            QuestionType = "MultipleChoice",
                            TimeLimitSeconds = 20
                        },
                        new
                        {
                            QuizID = 3,
                            LessonID = 1,
                            Points = 1,
                            QuestionText = "What does 'Teşekkürler' mean?",
                            QuestionType = "MultipleChoice",
                            TimeLimitSeconds = 20
                        },
                        new
                        {
                            QuizID = 4,
                            LessonID = 1,
                            Points = 1,
                            QuestionText = "How do you say 'My name is...' in Turkish?",
                            QuestionType = "MultipleChoice",
                            TimeLimitSeconds = 20
                        },
                        new
                        {
                            QuizID = 5,
                            LessonID = 1,
                            Points = 1,
                            QuestionText = "What does 'Güle güle' mean?",
                            QuestionType = "MultipleChoice",
                            TimeLimitSeconds = 20
                        },
                        new
                        {
                            QuizID = 6,
                            LessonID = 2,
                            Points = 1,
                            QuestionText = "What does 'Elma' mean?",
                            QuestionType = "MultipleChoice",
                            TimeLimitSeconds = 20
                        },
                        new
                        {
                            QuizID = 7,
                            LessonID = 2,
                            Points = 1,
                            QuestionText = "How do you say 'Water' in Turkish?",
                            QuestionType = "MultipleChoice",
                            TimeLimitSeconds = 20
                        },
                        new
                        {
                            QuizID = 8,
                            LessonID = 2,
                            Points = 1,
                            QuestionText = "What does 'Ekmek' mean?",
                            QuestionType = "MultipleChoice",
                            TimeLimitSeconds = 20
                        },
                        new
                        {
                            QuizID = 9,
                            LessonID = 2,
                            Points = 1,
                            QuestionText = "How do you say 'Tea' in Turkish?",
                            QuestionType = "MultipleChoice",
                            TimeLimitSeconds = 20
                        },
                        new
                        {
                            QuizID = 10,
                            LessonID = 2,
                            Points = 1,
                            QuestionText = "What does 'Süt' mean?",
                            QuestionType = "MultipleChoice",
                            TimeLimitSeconds = 20
                        });
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.QuizOption", b =>
                {
                    b.Property<int>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionID"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.HasKey("OptionID");

                    b.HasIndex("QuizID");

                    b.ToTable("QuizOptions");

                    b.HasData(
                        new
                        {
                            OptionID = 1,
                            IsCorrect = true,
                            OptionText = "Hello",
                            QuizID = 1
                        },
                        new
                        {
                            OptionID = 2,
                            IsCorrect = false,
                            OptionText = "Goodbye",
                            QuizID = 1
                        },
                        new
                        {
                            OptionID = 3,
                            IsCorrect = false,
                            OptionText = "Please",
                            QuizID = 1
                        },
                        new
                        {
                            OptionID = 4,
                            IsCorrect = false,
                            OptionText = "Sorry",
                            QuizID = 1
                        },
                        new
                        {
                            OptionID = 5,
                            IsCorrect = false,
                            OptionText = "İyi geceler",
                            QuizID = 2
                        },
                        new
                        {
                            OptionID = 6,
                            IsCorrect = true,
                            OptionText = "Günaydın",
                            QuizID = 2
                        },
                        new
                        {
                            OptionID = 7,
                            IsCorrect = false,
                            OptionText = "İyi akşamlar",
                            QuizID = 2
                        },
                        new
                        {
                            OptionID = 8,
                            IsCorrect = false,
                            OptionText = "Hoşça kal",
                            QuizID = 2
                        },
                        new
                        {
                            OptionID = 9,
                            IsCorrect = false,
                            OptionText = "You're welcome",
                            QuizID = 3
                        },
                        new
                        {
                            OptionID = 10,
                            IsCorrect = true,
                            OptionText = "Thank you",
                            QuizID = 3
                        },
                        new
                        {
                            OptionID = 11,
                            IsCorrect = false,
                            OptionText = "Excuse me",
                            QuizID = 3
                        },
                        new
                        {
                            OptionID = 12,
                            IsCorrect = false,
                            OptionText = "Congratulations",
                            QuizID = 3
                        },
                        new
                        {
                            OptionID = 13,
                            IsCorrect = true,
                            OptionText = "Benim adım...",
                            QuizID = 4
                        },
                        new
                        {
                            OptionID = 14,
                            IsCorrect = false,
                            OptionText = "Nasılsın?",
                            QuizID = 4
                        },
                        new
                        {
                            OptionID = 15,
                            IsCorrect = false,
                            OptionText = "Nerelisin?",
                            QuizID = 4
                        },
                        new
                        {
                            OptionID = 16,
                            IsCorrect = false,
                            OptionText = "Kaç yaşındasın?",
                            QuizID = 4
                        },
                        new
                        {
                            OptionID = 17,
                            IsCorrect = false,
                            OptionText = "Welcome",
                            QuizID = 5
                        },
                        new
                        {
                            OptionID = 18,
                            IsCorrect = true,
                            OptionText = "Goodbye (to someone leaving)",
                            QuizID = 5
                        },
                        new
                        {
                            OptionID = 19,
                            IsCorrect = false,
                            OptionText = "See you tomorrow",
                            QuizID = 5
                        },
                        new
                        {
                            OptionID = 20,
                            IsCorrect = false,
                            OptionText = "Good night",
                            QuizID = 5
                        },
                        new
                        {
                            OptionID = 21,
                            IsCorrect = false,
                            OptionText = "Banana",
                            QuizID = 6
                        },
                        new
                        {
                            OptionID = 22,
                            IsCorrect = true,
                            OptionText = "Apple",
                            QuizID = 6
                        },
                        new
                        {
                            OptionID = 23,
                            IsCorrect = false,
                            OptionText = "Orange",
                            QuizID = 6
                        },
                        new
                        {
                            OptionID = 24,
                            IsCorrect = false,
                            OptionText = "Grape",
                            QuizID = 6
                        },
                        new
                        {
                            OptionID = 25,
                            IsCorrect = true,
                            OptionText = "Su",
                            QuizID = 7
                        },
                        new
                        {
                            OptionID = 26,
                            IsCorrect = false,
                            OptionText = "Çay",
                            QuizID = 7
                        },
                        new
                        {
                            OptionID = 27,
                            IsCorrect = false,
                            OptionText = "Kahve",
                            QuizID = 7
                        },
                        new
                        {
                            OptionID = 28,
                            IsCorrect = false,
                            OptionText = "Süt",
                            QuizID = 7
                        },
                        new
                        {
                            OptionID = 29,
                            IsCorrect = false,
                            OptionText = "Cheese",
                            QuizID = 8
                        },
                        new
                        {
                            OptionID = 30,
                            IsCorrect = true,
                            OptionText = "Bread",
                            QuizID = 8
                        },
                        new
                        {
                            OptionID = 31,
                            IsCorrect = false,
                            OptionText = "Rice",
                            QuizID = 8
                        },
                        new
                        {
                            OptionID = 32,
                            IsCorrect = false,
                            OptionText = "Meat",
                            QuizID = 8
                        },
                        new
                        {
                            OptionID = 33,
                            IsCorrect = false,
                            OptionText = "Kahve",
                            QuizID = 9
                        },
                        new
                        {
                            OptionID = 34,
                            IsCorrect = false,
                            OptionText = "Su",
                            QuizID = 9
                        },
                        new
                        {
                            OptionID = 35,
                            IsCorrect = true,
                            OptionText = "Çay",
                            QuizID = 9
                        },
                        new
                        {
                            OptionID = 36,
                            IsCorrect = false,
                            OptionText = "Meyve suyu",
                            QuizID = 9
                        },
                        new
                        {
                            OptionID = 37,
                            IsCorrect = true,
                            OptionText = "Milk",
                            QuizID = 10
                        },
                        new
                        {
                            OptionID = 38,
                            IsCorrect = false,
                            OptionText = "Sugar",
                            QuizID = 10
                        },
                        new
                        {
                            OptionID = 39,
                            IsCorrect = false,
                            OptionText = "Salt",
                            QuizID = 10
                        },
                        new
                        {
                            OptionID = 40,
                            IsCorrect = false,
                            OptionText = "Honey",
                            QuizID = 10
                        });
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.QuizSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int?>("DeckId")
                        .HasColumnType("int");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("ScorePoints")
                        .HasColumnType("int");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimeLimitSeconds")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WrongCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizSessions");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.QuizSessionAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("bit");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int");

                    b.Property<int?>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("QuizSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("int");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("QuizSessionId");

                    b.HasIndex("SelectedOptionId");

                    b.ToTable("QuizSessionAnswers");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.StudyActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeckId")
                        .HasColumnType("int");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WordId")
                        .HasColumnType("int");

                    b.Property<int>("XpEarned")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("LessonId");

                    b.HasIndex("WordId");

                    b.HasIndex("UserId", "OccurredAt");

                    b.ToTable("StudyActivities");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<int>("DailyGoalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("int");

                    b.Property<string>("NativeLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetProficiencyLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalXp")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppleId")
                        .IsUnique()
                        .HasFilter("[AppleId] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("[GoogleId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserBadge", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserCategory", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("UserCategories");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserLearningPurpose", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("LearningPurposeId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "LearningPurposeId");

                    b.HasIndex("LearningPurposeId");

                    b.ToTable("UserLearningPurposes");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserProgress", b =>
                {
                    b.Property<int>("ProgressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressID"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastAccess")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ProgressID");

                    b.HasIndex("LessonID");

                    b.HasIndex("UserID", "LessonID")
                        .IsUnique();

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DailyReminders")
                        .HasColumnType("bit");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("bit");

                    b.Property<string>("DifficultyMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoundEffects")
                        .HasColumnType("bit");

                    b.Property<string>("TextSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThemeColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserWordProgress", b =>
                {
                    b.Property<long>("UserWordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserWordID"));

                    b.Property<double>("EaseFactor")
                        .HasColumnType("float");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("int");

                    b.Property<string>("LastRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MasteryLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("WordID")
                        .HasColumnType("int");

                    b.HasKey("UserWordID");

                    b.HasIndex("WordID");

                    b.HasIndex("UserID", "WordID")
                        .IsUnique();

                    b.ToTable("UserWordProgresses");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Vocabulary", b =>
                {
                    b.Property<int>("WordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordID"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeckId")
                        .HasColumnType("int");

                    b.Property<string>("ExampleSentence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("WordID");

                    b.HasIndex("DeckId");

                    b.ToTable("Vocabularies");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Deck", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.User", "User")
                        .WithMany("Decks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.LessonVocabulary", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.Lesson", "Lesson")
                        .WithMany("LessonVocabularies")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanGigaCards.Api.Entities.Vocabulary", "Vocabulary")
                        .WithMany("LessonVocabularies")
                        .HasForeignKey("WordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Quiz", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.Lesson", "Lesson")
                        .WithMany("Quizzes")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.QuizOption", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.Quiz", "Quiz")
                        .WithMany("Options")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.QuizSession", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanGigaCards.Api.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanGigaCards.Api.Entities.User", "User")
                        .WithMany("QuizSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.QuizSessionAnswer", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanGigaCards.Api.Entities.QuizSession", "QuizSession")
                        .WithMany("Answers")
                        .HasForeignKey("QuizSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanGigaCards.Api.Entities.QuizOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Quiz");

                    b.Navigation("QuizSession");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.StudyActivity", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanGigaCards.Api.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanGigaCards.Api.Entities.User", "User")
                        .WithMany("StudyActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LanGigaCards.Api.Entities.Vocabulary", "Vocabulary")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Deck");

                    b.Navigation("Lesson");

                    b.Navigation("User");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserBadge", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanGigaCards.Api.Entities.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserCategory", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.Category", "Category")
                        .WithMany("UserCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanGigaCards.Api.Entities.User", "User")
                        .WithMany("UserCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserLearningPurpose", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.LearningPurpose", "LearningPurpose")
                        .WithMany("UserLearningPurposes")
                        .HasForeignKey("LearningPurposeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanGigaCards.Api.Entities.User", "User")
                        .WithMany("UserLearningPurposes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningPurpose");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserProgress", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.Lesson", "Lesson")
                        .WithMany("UserProgresses")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanGigaCards.Api.Entities.User", "User")
                        .WithMany("UserProgresses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserSettings", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("LanGigaCards.Api.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.UserWordProgress", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.User", "User")
                        .WithMany("UserWordProgresses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LanGigaCards.Api.Entities.Vocabulary", "Vocabulary")
                        .WithMany("UserWordProgresses")
                        .HasForeignKey("WordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Vocabulary", b =>
                {
                    b.HasOne("LanGigaCards.Api.Entities.Deck", "Deck")
                        .WithMany("Flashcards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Category", b =>
                {
                    b.Navigation("UserCategories");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Deck", b =>
                {
                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.LearningPurpose", b =>
                {
                    b.Navigation("UserLearningPurposes");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Lesson", b =>
                {
                    b.Navigation("LessonVocabularies");

                    b.Navigation("Quizzes");

                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Quiz", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.QuizSession", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.User", b =>
                {
                    b.Navigation("Decks");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("QuizSessions");

                    b.Navigation("Settings");

                    b.Navigation("StudyActivities");

                    b.Navigation("UserBadges");

                    b.Navigation("UserCategories");

                    b.Navigation("UserLearningPurposes");

                    b.Navigation("UserProgresses");

                    b.Navigation("UserWordProgresses");
                });

            modelBuilder.Entity("LanGigaCards.Api.Entities.Vocabulary", b =>
                {
                    b.Navigation("LessonVocabularies");

                    b.Navigation("UserWordProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
